In [2]:
import spartan as st

Using backend cpu


In [3]:
import numpy as np
import sparse

# CPU Dense

In [4]:
A = st.DTensor.from_numpy(np.random.rand(3, 4))
print(A)

DTensor(
array([[0.37971278, 0.92770713, 0.77117777, 0.53611964],
       [0.26797079, 0.92839792, 0.41462598, 0.89409775],
       [0.95415388, 0.78644516, 0.62309603, 0.57903955]])
)


## Get Attributes

In [5]:
print(A.shape)
print(A.dtype)
print(A.T)

(3, 4)
float64
DTensor(
array([[0.37971278, 0.26797079, 0.95415388],
       [0.92770713, 0.92839792, 0.78644516],
       [0.77117777, 0.41462598, 0.62309603],
       [0.53611964, 0.89409775, 0.57903955]])
)


## Index and Slice

In [6]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

3
DTensor(
array([0.37971278, 0.92770713, 0.77117777, 0.53611964])
)
DTensor(
array([0.92770713, 0.92839792, 0.78644516])
)
DTensor(
array([[0.37971278, 0.92770713],
       [0.26797079, 0.92839792],
       [0.95415388, 0.78644516]])
)


## Reduction operations

In [7]:
print(A.sum())
print(A.sum(axis=0))

8.062544367878555
DTensor(
array([1.60183745, 2.64255021, 1.80889977, 2.00925693])
)


In [8]:
print(st.sum(A))
print(st.sum(A, axis=0))

8.062544367878555
DTensor(
array([1.60183745, 2.64255021, 1.80889977, 2.00925693])
)


## Binary operations

In [9]:
B = st.DTensor.from_numpy(np.random.rand(3, 4))

In [10]:
print(A+B)
print(st.add(A, B))

DTensor(
array([[1.34703334, 0.98923887, 1.72938615, 0.98395904],
       [1.03099973, 1.70951819, 1.30311079, 1.31403774],
       [1.78687619, 1.63515756, 1.30643332, 1.31955874]])
)
DTensor(
array([[1.34703334, 0.98923887, 1.72938615, 0.98395904],
       [1.03099973, 1.70951819, 1.30311079, 1.31403774],
       [1.78687619, 1.63515756, 1.30643332, 1.31955874]])
)


In [11]:
print(A.dot(B.T))
print(st.dot(A, B.T))

DTensor(
array([[1.40343192, 1.92470049, 2.02753325],
       [1.11404989, 1.67351619, 1.95651402],
       [1.82773656, 2.13912849, 2.31658563]])
)
DTensor(
array([[1.40343192, 1.92470049, 2.02753325],
       [1.11404989, 1.67351619, 1.95651402],
       [1.82773656, 2.13912849, 2.31658563]])
)


# CPU Sparse

In [12]:
A = np.random.rand(3, 4)
A[A<0.8] = 0
A = st.STensor.from_numpy(A)
print(A)
print(A.todense())

STensor(<COO: shape=(3, 4), dtype=float64, nnz=2, fill_value=0.0>)
DTensor(
array([[0.        , 0.        , 0.        , 0.86224537],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.95945863, 0.        ]])
)


## Get Attributes

In [13]:
print(A.shape)
print(A.dtype)
print(A.T)

(3, 4)
float64
STensor(<COO: shape=(4, 3), dtype=float64, nnz=2, fill_value=0.0>)


## Index and Slice

In [14]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

3
STensor(<COO: shape=(4,), dtype=float64, nnz=1, fill_value=0.0>)
STensor(<COO: shape=(3,), dtype=float64, nnz=0, fill_value=0.0>)
STensor(<COO: shape=(3, 2), dtype=float64, nnz=0, fill_value=0.0>)


## Reduction operations

In [15]:
print(A.sum())
print(A.sum(axis=0).todense())

1.8217040040234693
DTensor(
array([0.        , 0.        , 0.95945863, 0.86224537])
)


In [16]:
print(st.sum(A))
print(st.sum(A, axis=0).todense())

1.8217040040234693
DTensor(
array([0.        , 0.        , 0.95945863, 0.86224537])
)


## Binary operations

In [17]:
B = np.random.rand(3, 4)
B[B<0.8] = 0
B = st.STensor.from_numpy(B)

In [18]:
print(A+B)
print((A+B).todense())
print(st.add(A, B))
print(st.add(A, B).todense())

STensor(<COO: shape=(3, 4), dtype=float64, nnz=3, fill_value=0.0>)
DTensor(
array([[0.        , 0.        , 0.        , 0.86224537],
       [0.        , 0.        , 0.        , 0.        ],
       [0.87014047, 0.        , 0.95945863, 0.        ]])
)
STensor(<COO: shape=(3, 4), dtype=float64, nnz=3, fill_value=0.0>)
DTensor(
array([[0.        , 0.        , 0.        , 0.86224537],
       [0.        , 0.        , 0.        , 0.        ],
       [0.87014047, 0.        , 0.95945863, 0.        ]])
)


In [19]:
print(A.dot(B.T))
print(A.dot(B.T).todense())
print(st.dot(A, B.T))
print(st.dot(A, B.T).todense())

STensor(<COO: shape=(3, 3), dtype=float64, nnz=0, fill_value=0.0>)
DTensor(
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
)
STensor(<COO: shape=(3, 3), dtype=float64, nnz=0, fill_value=0.0>)
DTensor(
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
)


# GPU Dense

In [20]:
import sys
sys.path.append('../../')

In [21]:
import spartan as st

st.load_backend('gpu')

Using backend gpu


In [22]:
import torch

In [23]:
A = st.DTensor(torch.rand(3, 4))

## Attributes

In [24]:
print(A.shape)
print(A.dtype)
print(A.T)

DTensor(
tensor([3, 4], device='cuda:0')
)
torch.float32
DTensor(
tensor([[0.9952, 0.7491, 0.8645],
        [0.1331, 0.2979, 0.5710],
        [0.5118, 0.8959, 0.7612],
        [0.1952, 0.7256, 0.5922]], device='cuda:0')
)


## Slice

In [25]:
print(len(A))
print(A[0])
print(A[:, 1])
print(A[:, 0:2])

3
DTensor(
tensor([0.9952, 0.1331, 0.5118, 0.1952], device='cuda:0')
)
DTensor(
tensor([0.1331, 0.2979, 0.5710], device='cuda:0')
)
DTensor(
tensor([[0.9952, 0.1331],
        [0.7491, 0.2979],
        [0.8645, 0.5710]], device='cuda:0')
)


## Reduction Operations

In [26]:
print(A.sum())
print(A.sum(axis=0))

7.292748928070068
DTensor(
tensor([2.6089, 1.0020, 2.1689, 1.5130], device='cuda:0')
)


In [27]:
print(st.sum(A))
print(st.sum(A, axis=0))

7.292748928070068
DTensor(
tensor([2.6089, 1.0020, 2.1689, 1.5130], device='cuda:0')
)


## Binary Operations

In [28]:
B = st.DTensor(torch.rand(3, 4))

In [29]:
print(A+B)
print(st.add(A, B))

DTensor(
tensor([[1.5273, 0.2267, 0.6178, 0.3074],
        [1.2462, 0.9045, 1.1297, 0.9067],
        [1.5285, 1.3404, 1.5518, 0.7043]], device='cuda:0')
)
DTensor(
tensor([[1.5273, 0.2267, 0.6178, 0.3074],
        [1.2462, 0.9045, 1.1297, 0.9067],
        [1.5285, 1.3404, 1.5518, 0.7043]], device='cuda:0')
)


In [30]:
print(A.dot(B.T))
print(st.dot(A, B.T))

DTensor(
tensor([[0.6182, 0.7304, 1.1897],
        [0.6029, 0.8939, 1.5163],
        [0.6606, 1.0613, 1.6816]], device='cuda:0')
)
DTensor(
tensor([[0.6182, 0.7304, 1.1897],
        [0.6029, 0.8939, 1.5163],
        [0.6606, 1.0613, 1.6816]], device='cuda:0')
)


## GPU Sparse
**Notice**: Some oeprations are not supported for GPU STensor yet!

In [31]:
import scipy.sparse as ssp

In [32]:
A = np.random.rand(3, 4)
A[A<0.8] = 0

In [33]:
A = np.random.rand(3, 4)
A[A<0.8] = 0
A = st.STensor.from_numpy(A)
print(A)
print(A.todense())

STensor(
tensor(indices=tensor([[1, 2, 2, 2],
                       [2, 0, 1, 3]]),
       values=tensor([0.8536, 0.8730, 0.9592, 0.8267]),
       device='cuda:0', size=(3, 4), nnz=4, dtype=torch.float64,
       layout=torch.sparse_coo)
)
DTensor(
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.8536, 0.0000],
        [0.8730, 0.9592, 0.0000, 0.8267]], device='cuda:0',
       dtype=torch.float64)
)


## Attributes

In [34]:
print(A.shape)
print(A.dtype)
# print(A.T)

DTensor(
tensor([3, 4], device='cuda:0')
)
torch.float64


## Index and Slice
**Notice**: Pytorch GPU sparse tensor doesn't support complex slice yet!

In [35]:
print(len(A))
print(A[0])

3
STensor(
tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0,)),
       device='cuda:0', size=(4,), nnz=0, dtype=torch.float64,
       layout=torch.sparse_coo)
)


## Reduction operations

In [36]:
print(A.sum())
print(A.sum(axis=0).todense())

3.5125456713899603
DTensor(
tensor([0.8730, 0.9592, 0.8536, 0.8267], device='cuda:0', dtype=torch.float64)
)


In [37]:
# print(st.sum(A))
# print(st.sum(A, axis=0).todense())

## Binary operations

In [38]:
B = np.random.rand(3, 4)
B[B<0.8] = 0
B = st.STensor.from_numpy(B)

In [39]:
print(A+B)
print((A+B).todense())
# print(st.add(A, B))
# print(st.add(A, B).todense())

STensor(
tensor(indices=tensor([[1, 2, 2, 2, 1, 2, 2],
                       [2, 0, 1, 3, 0, 1, 2]]),
       values=tensor([0.8536, 0.8730, 0.9592, 0.8267, 0.8362, 0.9146, 0.8965]),
       device='cuda:0', size=(3, 4), nnz=7, dtype=torch.float64,
       layout=torch.sparse_coo)
)
DTensor(
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.8362, 0.0000, 0.8536, 0.0000],
        [0.8730, 1.8738, 0.8965, 0.8267]], device='cuda:0',
       dtype=torch.float64)
)
